auto_lock_button: x2
conf: 0.75
delay: 0
detect_length: 640
enemy_list:
- enemy
label_list:
- enemy
- down
- friend
max_lock_dis: 200
max_pid_dis: 30
max_step_dis: 120
mouse_button_1: left
mouse_button_2: right
onnx_path: weights/best_apex.onnx
pidx_kd: 3.51
pidx_ki: 0.0
pidx_kp: 1.2
pidy_kd: 0.24
pidy_ki: 0.0
pidy_kp: 1.22
pos_factor: 0.08
print_button: true
resolution_x: 1920
resolution_y: 1080
save_screenshot: false
smooth: 0.48
speed_test: true
trt_path: weights/best_apex.trt
visualization: true
